onboarding = false
[theme]
name = "tokyo-night"

auto_switch = false

[theme.custom]
accent = "#4d9375"
panel_bg = "#000000"
surface0 = "#121212"
surface1 = "#121212"
surface_dim = "#0f1d17"
overlay0 = "#777777"
overlay1 = "#bfbaaa"
text = "#dbd7ca"
subtext0 = "#bfbaaa"
mauve = "#d9739f"
green = "#4d9375"
yellow = "#e6cc77"
red = "#cb7676"
blue = "#6394bf"
teal = "#5eaab5"
peach = "#e6cc77"

[ui.toast]
delivery = "system"

[experimental]
kitty_graphics = true
