model = "gpt-6-astra"
model_provider = "openai"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
approvals_reviewer = "user"
approval_policy = "never"
sandbox_mode = "danger-full-access"

notify = ["/Users/kvoon/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended", "--previous-notify", "[\"\\/Users\\/kvoon\\/.bun\\/bin\\/bun\",\"\\/Users\\/kvoon\\/.confirmo\\/hooks\\/confirmo-codex-hook.js\"]"]

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."trade@plugins-cli"]
enabled = false

[plugins."build-macos-apps@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = false

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[tui]
theme = "gruvbox-light"
status_line = [
  "model-with-reasoning",
  "current-dir",
  "five-hour-limit",
  "weekly-limit"
]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
gpt-6-astra = 4

[notice]
hide_full_access_warning = true

[features]
hooks = true
terminal_resize_reflow = true
goals = true
prevent_idle_sleep = true
js_repl = false

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/kvoon/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/kvoon/.codex/.tmp/bundled-marketplaces/openai-bundled"

[desktop]
ambient-suggestions-enabled = true
appearanceTheme = "system"
appearanceLightCodeThemeId = "notion"
appearanceDarkCodeThemeId = "codex"
sansFontSize = 16
codeFontSize = 13
composerEnterBehavior = "enter"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
git-pull-request-merge-method = "squash"
git-show-sidebar-pr-icons = true
git-commit-instructions = """
commit message should follow Conventional Commits:

<type>[optional scope]: <description>

[optional body]

[optional footer(s)]"""
selected-avatar-id = "stacky"
conversationDetailMode = "STEPS_PROSE"
git-create-pull-request-as-draft = false
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"
avatar-overlay-mascot-width-px = 110

  [desktop.appearanceLightChromeTheme]
  accent = "#3183d8"
  accentSource = "custom"
  contrast = 45
  ink = "#37352f"
  opaqueWindows = true
  surface = "#ffffff"
  fonts = { }

    [desktop.appearanceLightChromeTheme.semanticColors]
    diffAdded = "#008000"
    diffRemoved = "#a31515"
    skill = "#0000ff"

  [desktop.appearanceDarkChromeTheme]
  accent = "#0169cc"
  contrast = 60
  ink = "#fcfcfc"
  opaqueWindows = true
  surface = "#111111"

    [desktop.appearanceDarkChromeTheme.fonts]
    ui = "Inter"

    [desktop.appearanceDarkChromeTheme.semanticColors]
    diffAdded = "#00a240"
    diffRemoved = "#e02e2a"
    skill = "#b06dff"

  [desktop.open-in-target-preferences]
  global = "fileManager"

    [desktop.open-in-target-preferences.perPath]
    "/Users/kvoon/.codex/worktrees/b20f/oduck" = "ghostty"
    "/Users/kvoon/i/kvoon.me" = "vscode"
    "/Users/kvoon/weila/weila-js-sdk" = "fileManager"
    "/Users/kvoon/weila/weila-webview-realname-auth" = "vscode"
    "/Users/kvoon/weila/weila-work-and-sdk" = "vscode"
    "/Users/kvoon/i/oduck" = "ghostty"
    "/Users/kvoon/.codex/worktrees/744b/oduck" = "fileManager"
    "/Users/kvoon/.codex/worktrees/b637/oduck" = "ghostty"
    "/Users/kvoon/Documents/bookmarks" = "fileManager"
    "/Users/kvoon/i/bb" = "vscode"
    "/Users/kvoon/f/mi_remote_control" = "fileManager"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/kvoon/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/kvoon/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.908.70816"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/kvoon/.codex/plugins/cache/openai-bundled/browser/26.908.70816/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/kvoon/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[hooks.state]

[hooks.state."/Users/kvoon/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:d54bdde9870a3baf79050b5c9b5840093f2dfa2661a3c25e11185bb00fbad34b"
enabled = true

[hooks.state."browser@openai-bundled:plugin.json#hooks[0]:stop:0:0"]
trusted_hash = "sha256:317a07045dfc95aef2e80c55428a2f817e2768be867e3b1ef29a73da8636ae7f"

[hooks.state."chrome@openai-bundled:plugin.json#hooks[0]:stop:0:0"]
trusted_hash = "sha256:317a07045dfc95aef2e80c55428a2f817e2768be867e3b1ef29a73da8636ae7f"

[shell_environment_policy.set]
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "7fe0e1c59da4bc68f9d6ab81ae8d349b53fee44b074f49be0effbc1105a5f1d3"

[projects."/Users/kvoon/f/mi_remote_control"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-02/hatch-pet-users-kvoon-codex-skills"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-03/ah"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-03/w-s-m"]
trust_level = "trusted"

[projects."/Users/kvoon/weila/vois-app-webview-next"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-04/new-chat"]
trust_level = "trusted"

[projects."/Users/kvoon/f/pi-from-scratch"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-04/es"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-04/new-chat-2"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-04/new-chat-3"]
trust_level = "trusted"

[projects."/Users/kvoon/weila/weila-webview-realname-auth"]
trust_level = "trusted"

[projects."/Users/kvoon"]
trust_level = "trusted"

[projects."/Users/kvoon/f/herdr-palette"]
trust_level = "trusted"

[projects."/Users/kvoon/i/oxlint-config"]
trust_level = "trusted"

[projects."/Users/kvoon/i/pi-extensions"]
trust_level = "trusted"

[projects."/Users/kvoon/.config"]
trust_level = "trusted"

[projects."/Users/kvoon/.pi"]
trust_level = "trusted"

[projects."/Users/kvoon/Documents/Codex/2026-09-15/esfp-chatgpt-conversation-6a8128c0-3c88-83ec"]
trust_level = "trusted"

[[skills.config]]
path = "/Users/kvoon/.config/dotfiles/.agents/skills/obsidian-vault/SKILL.md"
enabled = false

[[skills.config]]
path = "/Users/kvoon/.config/dotfiles/.agents/skills/obsidian-markdown/SKILL.md"
enabled = false

[apps.connector_2128aebfecb84f64a069897515042a44]
enabled = false

[apps.connector_5f3c8c41a1e54ad7a76272c89e2554fa]
enabled = false

[apps.connector_68de829bf7648191acd70a907364c67c]
enabled = false

[apps.connector_69312da8e4dc81919370cb86fd172b6c]
enabled = false

[apps.connector_openai_hotline]
enabled = false

[apps.asdk_app_694546cd042881919bb746a8dc300f38]
enabled = false

[apps.asdk_app_69c4d4163c8c819183a9bdcf6d2ac262]
enabled = false
